// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace rmbcsharpaspdemo {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Label apiKeyLabel;
		
		protected System.Web.UI.WebControls.PlaceHolder messageBoxPlaceHolder;
		
		protected System.Web.UI.HtmlControls.HtmlForm createDropForm;
		
		protected System.Web.UI.WebControls.TextBox newDropNameTextBox;
		
		protected System.Web.UI.WebControls.Button createDropButton;
		
		protected System.Web.UI.WebControls.Button createRandomDropButton;
		
		protected System.Web.UI.WebControls.Repeater dropListRepeater;
	}
}
