// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace rmbcsharpaspdemo {
	
	
	public partial class ViewDrop {
		
		protected System.Web.UI.WebControls.Label dropNameLabel;
		
		protected System.Web.UI.HtmlControls.HtmlForm addAssetForm;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden api_key;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden drop_name;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden redirect_to;
		
		protected System.Web.UI.WebControls.PlaceHolder messageBoxPlaceHolder;
		
		protected System.Web.UI.WebControls.Repeater assetListRepeater;
	}
}
